import Navigation from "@/components/navigation/Navigation";
import "./globals.css";
import { Cabin, Hanken_Grotesk } from "next/font/google";
import Footer from "@/components/footer/Footer";

export const cabin = Cabin({ subsets: ["latin"], display: "swap", variable: "--font-cabin" });

export const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-hanken",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
